use crate::app::LoaderMessage;

mod toolbar;
mod sidebar;
mod navigator;
mod histogram;
mod adjustments;
mod metadata;
mod keywording;
mod folders;
mod sidebar_utils;
mod thumbnails;
mod dialogs;
mod settings_dialog;
mod go_to_dialog;
mod move_dialog;
mod command_palette;
mod image_view;
mod main;
